name: semaphoreci_flutter_demo
description: SemaphoreCI Flutter Demo

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  very_good_analysis: ^3.0.2
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
